# --- Datos del sitio ---
url: https://eagomezdaza.github.io
baseurl: /Mi-portafolio
title: Mi portafolio
description: "Bienvenido a mi portafolio personal"
theme: jekyll-theme-primer

# --- Markdown / Kramdown ---
markdown: kramdown
kramdown:
  input: GFM            # GitHub Flavored Markdown
  hard_wrap: false
  parse_block_html: true  # <— Permite HTML de bloque dentro de .md

# --- Build robusto ---
permalink: pretty
timezone: America/Santiago

# GitHub Pages plugins permitidos
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Archivos y carpetas a excluir del build
exclude:
  - venv
  - .venv
  - node_modules
  - .github
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE
  - README.md
  - .python-version
  - .env
  - .env.*           # por si guardas variantes
  - _site            # evita arrastrarlo si lo generas local
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - package-lock.json
  - yarn.lock

# Mantener (por si sirves archivos estáticos fuera de /assets)
keep_files:
  - assets

# Defaults útiles (opcional)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Sitemap
sass:
  style: compressed


