title: Mi portafolio
description: "Bienvenido a mi portafolio personal"
theme: jekyll-theme-primer
markdown: kramdown
exclude:
  - venv
  - .venv
  - node_modules
  - .github
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE

